### PR TITLE
Add slides PDF (version as of July 14, 2023)

### PR DESCRIPTION
**Pull request by rnikutta**
@jacquesalice Would you mind briefly checking the added slides PDF? It's meant for submission to ADASS, but we may edit it more until Nov. Thanks.

### CODE REVIEW

**Review by jacquesalice — CHANGES_REQUESTED** [review]
Thanks @rnikutta ! Some things:

1. On the first page, it looks like the "Discovering Our Universe Together" is a bit chopped off at the bottom. Can you shift that a little upwards?
2. Some pages are missing their page numbers: 6, 11, 14 (looks like it's behind the Contents table), 15 **----> I just added them!**
4. On page 7, you have DECaLS DR 3 through 10 -- is this the Legacy Surveys? Should we have it listed as Legacy Surveys (LS) instead? Since that's what the dataset is called in our database, website, and notebooks...
5. On page 9, for the Notes in the "Sky exploration" row you could add some of the available catalogs to choose from, i.e. "SMASH, DES, NSC, Gaia"
6. On page 10, the screenshot you have of our User Manual and Helpdesk say NOAO. Can you take new screenshots of those pages? **----> I just updated them!**

**Comment by rnikutta** [comment]
Thanks @jacquesalice Fixed all points and saw you were doing page 10 fixes. Ping me when you're done with it :) I'll then export the PDF and push a commit here.

**Comment by jacquesalice** [comment]
@rnikutta done now!

**Comment by rnikutta** [comment]
@jacquesalice New PDF pushed. Thanks!

**Review by jacquesalice — APPROVED** [review]

**Pull request merged**
